allow_net_connect: true
allow_push_notification: true

omniauth:
  facebook:
    app_id: <%= ENV['FACEBOOK_APP_ID'] %>
    app_secret: <%= ENV['FACEBOOK_APP_SECRET'] %>
  twitter:
    app_key: hkVnha9e4asFz2zH5sEma2vHn
    app_secret: Gc9RV7ko8kQo40KMiFI4EfpoWNdIU7PJoCXN8npg6USA1cDe1j
  fitbit:
    client_id:
    client_secret:
    redirect_uri: 'http://localhost:3000/fitbit/auth/authorized_callback'
    scope: [activity sleep weight]
basic_auth:
  api:
    user: "singularityLab"
    pass: "welovesingularity"
gcm:
  api_key: "AIzaSyCQgGSJOBtFG6B4EcWZa2azAlAQ0IMxOdo"
apns:
  certificate_file_names:
    - 'dummy_for_test.pem'
admin_password:
  secret_key: 'cb98d90c2d09a5f7cb8beb7fa94e7cafd3689ce203d92a5a01'
  cipher: 'aes-256-cbc'
test_email: engineers_finc@googlegroups.com
base_url: 'http://127.0.0.1'
finc_store:
  base_url: 'http://127.0.0.1'
  sb:
    base_url: 'http://127.0.0.1'
  api:
    access_grant: 'gcSEuY4LTdGgkBTmSXPRhxtBsapexBzurL2Sx4cV'
finc_app:
  consumer_key: 'M4HXT1y4-xuyoKE1DgHu4wtWyYX4P5BaTxsWf7Kp'
  consumer_key_for_wellness_survey: 'lBVinAslijzcf1CtxDYYQewIMEUJsDxxuk3fBVpN'
  consumer_key_for_customer_manager: 'm2cMtQBXwrkBA-cnBQAsDqaCay4fLQghtn9pQEu9iJ79uCKrW2oas_xijzj3'
  consumer_key_for_wellness_ai: 'gh9nErE8/zOhcgVf0bGXJfnF3ckLea6O4CSZ2wEQ'
  consumer_key_for_online_works: 'ON46f6xgRszoj-lmaIPCcizyRdA2okHy8pRTgPGx'
genetic_test:
  database:
    database: "genetic_test_development"
  api_version: v1
  api:
    access_grant: 'b34f70f14361426776f8f3df39dc110776a024219d620700d60f6570d90803a4'
  paper_media_tmp_user_password: '1234joyfit'
customer_manager:
  api:
    version: v1
    access_grant: 'de9da7a04e7bb21b0219a93a8b1b5ed98d00cf4c24f8f9701e1fb5062ca18ab5'
wellness_survey:
  api:
    version: v1
    access_grant: 'Bu8qQPQ9YjcPWruoag_t_GRXxn9CyRmgPNG4DCJT'
    base_url: 'http://127.0.0.1'
  light_survey_url: 'http://127.0.0.1/oauth/authorization'
  personal_survey_url: 'http://127.0.0.1/oauth/authorization/personal_survey'
  finish_url: 'fincapp://wellness-survey-callback'
  mental_care_url: 'http://127.0.0.1/oauth/authorization/mental_care'
wellness_ai:
  api:
    version: v1
    access_grant: 'o2PtCedv5V1ATXAUTRsAf-9GhZ41Lx4E6AchCnzn_7tKc66k8uL1dfxH-pqcusZr'
    application_token: 'development'
    base_url: 'http://127.0.0.1'
finc_account_manager:
  enable: true
  api:
    version: v1
    access_grant: '4CUnecg4KacURjSy8Hbx22RNkiL8zaLSN2HaXTUCyQD-XcdkPFS3DKyRjhRr'
    base_url: 'http://127.0.0.1'
o2o_client:
  base_url: ''
o2o:
  api:
    application_token: ''
  base_url: ''

fi_chat:
  api:
    base_url:
    access_grant: fichataccessgrant
    application_token: fichataccessgrant
  direct_chat:
    official_account:
      finc_information_id: 1
      broadcast_sendable_ids:
        - 1

fi_chat_client:
  api:
    base_url: 'https://local.finc.com'

company_account_manager:
  api:
    base_url:
    access_grant: 'oh_4D6AHdDXnttpGKZZRUxxLsePJUZaEPXHmypoQ'
    application_token: 'oh_4D6AHdDXnttpGKZZRUxxLsePJUZaEPXHmypoQ'

online_works:
  api:
    base_url:

finc_app_web_client:
  base_url:

push_notifier:
  api:
    access_grant:
    base_url:

rankie:
  api:
    access_grant:
    base_url:
  event:
    tft:
      ranking_id: 280
      tab_ids:
        - 66561
        - 66562
        - 66563

activity_timeline:
  api:
    base_url:
    application_token:

try_content:
  tmp:
    sakura_comment:
      enabled_user_ids:
        - 1

aws:
  access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  fog_directory: "requl-development"
  cloudfront:
    base_url: 'https://dt1r5cs4p5dys.cloudfront.net'
    private_key_file_name: ''
    key_pair_id: ''
  elastic_transcoder:
    common:
      pipeline_id: '1470731692492-ywnoh8'
      sqs_endpoint: 'https://sqs.ap-northeast-1.amazonaws.com/759549166074/elastic_transcoder_development'
    try_common:
      preset_id:
        movie: '1476404155275-p02wal'
        mobile_movie: '1476404155275-p02wal'
        webm_movie: '1351620000001-100240'
    promotion_movie:
      pipeline_id: '1470731692492-ywnoh8'
      sqs_endpoint: 'https://sqs.ap-northeast-1.amazonaws.com/759549166074/elastic_transcoder_development'
      preset_id:
        mobile_movie: '1473999882571-7tqhn8'
        web_movie: '1351620000001-100240'
      uploadable_official_account_ids:
        - 1
  sns:
    concierge:
      topic_name: 'LOCAL TOPIC NAME'
  cognito:
    identity_pool_id: <%= ENV['AWS_COGNITO_IDENTITY_POOL_ID'] %>
    identity_provider_name: <%= ENV['AWS_COGNITO_IDENTITY_PROVIDER_NAME'] %>

secrets:
  secret_key_base: ed6a7b55dd4e8afeadd390066c76df88223810c0fcdf95628d7222ba4b2f8c8e4cdb2d0fa039bf8004d3aece62d0514cfa8303cac7a3c6c2c32eab56a1972a04

mailer:
  host: 'localhost:3000'
  user_name: 'YOURMAILEREMAIL@finc.com'
  admin:
    from: オンラインワークス事務局 <info-ow@finc.co.jp>
    user_name: info-ow@finc.co.jp
  user:
    from: FiNC <info@finc.com>
    user_name: 'info@finc.com'
  finc_developer:
    from: FiNC Developer <info@finc.com>
    user_name: 'info@finc.com'
    bcc: []
  send_only:
    from: '【FiNCサポートセンター（自動配信）】 <no-reply-fincapp@finc.com>'
    user_name: no-reply-fincapp@finc.com
    bcc:
      default:
        - no-reply-fincapp@finc.com
      need_to_reply:
        - no-reply-fincapp@finc.com
        - support-fincapp@finc.com
  support_center:
    from: '【FiNCサポートセンター】 <support-fincapp@finc.com>'
    user_name: support-fincapp@finc.com
  default:
    bcc: []

partner_organization:
  blank_mail:
    address: 'apply-stg@inbound.finc.com'
    access_token: <%= ENV['PO_BLANKMAIL_ACCESS_TOKEN'] %>

slack:
  finc_account_manager:
    channel_url: ''
    test_channel_url: ''
    channel: '#fam_test'
  requl_mobile:
    url: ''
    channel: '#diet_coach_develop'
  fi_chat:
    url: ''
    channel: ''
  activity_timeline:
    url: ''
    channel: ''
  rake:
    finc_app_tag:
      url: 'https://finc.slack.com'
      channel: '#dc_warning_staging'

db:
  default:
    username: root
    password: root
    host: 127.0.0.1
    port: 3306
  genetic_test:
    username: 'YOUR DB USERNAME HERE'
    password: 'YOUR DB PASSWORD HERE'
    database: genetic_test_development
    socket: /tmp/mysql.sock

redis:
  host: localhost
  port: 6379
  namespace: <%= [Rails.application.class.parent_name, Rails.env].join(':') %>

sidekiq:
  redis:
    host: localhost
    port: 6379

errbit:
  api_key: 4c9a8ba8c4ee17ac0d20a7f746e865e8

finc_services:
  access_grants:
    - 219bdc9725e75b85b94a1a40716732f5586212c7b5987d27a5db1d39876acfbe
    - de9da7a04e7bb21b0219a93a8b1b5ed98d00cf4c24f8f9701e1fb5062ca18ab5
    - Bu8qQPQ9YjcPWruoag_t_GRXxn9CyRmgPNG4DCJT
    - o2PtCedv5V1ATXAUTRsAf-9GhZ41Lx4E6AchCnzn_7tKc66k8uL1dfxH-pqcusZr
    - 4CUnecg4KacURjSy8Hbx22RNkiL8zaLSN2HaXTUCyQD-XcdkPFS3DKyRjhRr
    - fichataccessgrant
    - VHrs1cfyYadYu3Kb8RSP4V_XEpsfggjzeKmJ5nBh

from_scratch:
  sftp:
    server_host: ftp.fs-bdash.com
    username: bd_bmhqca_1
    identity_key: /home/ubuntu/.ssh/f_scratch_rsa
sb:
  cindy:
    client_id: CHXvBFRKG3YKYmBFIqYRa1j7IeP2upPY
    client_secret: TENLGKw7epxHnntXLt1DJ7JVPqlwIeEZ
    authentication:
      fetch_code:
        url: 'http://id.dev.whitecloud.jp/sbid_auth/type1/2.0/authorization.php'
        redirect_uri_for_sign_up: 'https://staging-pksapp.finc.com/users/oauth/cindy/callback'
        redirect_uri_for_sign_in: 'https://staging-pksapp.finc.com/users/oauth/cindy_sign_in/callback'
        redirect_uri_for_cancel: 'https://staging-pksapp.finc.com/users/oauth/cindy/callback/cancel'
      fetch_access_token:
        url: 'http://ifapi.id.dev.whitecloud.jp/sbid/2.0/sbid_token_endpoint/token'
        redirect_uri: 'https://staging-pksapp.finc.com/users/oauth/cindy/callback'
      check_contracted:
        url: 'http://ifapi.id.dev.whitecloud.jp/sbid/2.0/sbid_token_endpoint/checktoken'
    service:
      contents_service_id: '139'
      usage_status:
        url: 'http://ifapi.id.dev.whitecloud.jp/sgw/cdp/GetServiceUsageStatus'
      start_billing:
        url: 'http://ifapi.id.dev.whitecloud.jp/sgw/cdp/StartBilling'
      stop_billing:
        url: 'http://ifapi.id.dev.whitecloud.jp/sgw/cdp/StopBilling'
  healthcare:
    application_id: 'ux3C38lJeNXZhF9H8NOFmet0uszSqzdnQWCMqxHIItPawlms4bQc22rQCzwQZGjTisWgKQN97T7'
    summary:
      url: 'https://stg.healthcare.mb.softbank.jp/stg/ext/v1/api/get_bodycomp_summary.php'
    detail:
      url: 'https://stg.healthcare.mb.softbank.jp/stg/ext/v1/api/get_ac_bodycomp_detail.php'
    started:
      url: 'https://stg.healthcare.mb.softbank.jp/stg/ext/v1/webview/login.php'
      redirect_uri: 'https://staging-pksapp.finc.com/sb/services/bodycomposition/started'
    canceled:
      url: 'https://stg.healthcare.mb.softbank.jp/stg/ext/v1/webview/logout.php'
      redirect_uri: 'https://staging-pksapp.finc.com/sb/services/bodycomposition/canceled'
  sftp:
    host: ftp0001
    username: ubuntu
    options:
      identity_keys: '/path/to/your/identity_key'
      port: 22

girls_award:
  host: 'localhost'
  protocol: 'http'

laerdal:
  application_token: development_token

sbi_life:
  tmp_user:
    sign_up_with_email:
      auth_token: <%= ENV['SBI_LIFE_TMP_USER_SIGN_UP_WITH_EMAIL_AUTH_TOKEN'] %>
    new:
      blank_mail:
        mailto_address: 'sbi-apply-dev@inbound.finc.com'

sfdc:
  help_url:
    consumer_key: <%= ENV['SFDC_HELP_URL_CONSUMER_KEY'] %>
    salt: <%= ENV['SFDC_HELP_URL_SALT'] %>
    url: 'https://dev3-finc.cs6.force.com/faq'

pre_registration_user:
  authentication_token: <%= ENV['PRE_REGISTRATION_USER_AUTHENTICATION_TOKEN'] %>
