allow_net_connect: true
allow_push_notification: true

omniauth:
  facebook:
    app_id: 193538350855275
    app_secret: 486ef72737ddbcce023528971421be30
  twitter:
    app_key: hkVnha9e4asFz2zH5sEma2vHn
    app_secret: Gc9RV7ko8kQo40KMiFI4EfpoWNdIU7PJoCXN8npg6USA1cDe1j
basic_auth:
  api:
    user: "singularityLab"
    pass: "welovesingularity"
gcm:
  api_key: "AIzaSyCQgGSJOBtFG6B4EcWZa2azAlAQ0IMxOdo"
apns:
  certificate_file_names:
    - 'server_certificates_sandbox.pem'
admin_password:
  secret_key: 'cb98d90c2d09a5f7cb8beb7fa94e7cafd3689ce203d92a5a01'
  cipher: 'aes-256-cbc'
test_email: engineers_finc@googlegroups.com
base_url: 'http://dev-app.finc.com'
finc_store:
  base_url: 'http://dev-store.finc.com'
finc_app:
  consumer_key: 'M4HXT1y4-xuyoKE1DgHu4wtWyYX4P5BaTxsWf7Kp'
  consumer_key_for_wellness_survey: 'lBVinAslijzcf1CtxDYYQewIMEUJsDxxuk3fBVpN'
  consumer_key_for_customer_manager: 'm2cMtQBXwrkBA-cnBQAsDqaCay4fLQghtn9pQEu9iJ79uCKrW2oas_xijzj3'
  consumer_key_for_wellness_ai: 'gh9nErE8/zOhcgVf0bGXJfnF3ckLea6O4CSZ2wEQ'
genetic_test:
  database:
    database: "genetic_test_development"
  api_version: v1
  api:
    access_grant: 'b34f70f14361426776f8f3df39dc110776a024219d620700d60f6570d90803a4'
customer_manager:
  api:
    version: v1
    access_grant: 'de9da7a04e7bb21b0219a93a8b1b5ed98d00cf4c24f8f9701e1fb5062ca18ab5'
wellness_survey:
  api:
    version: v1
    access_grant: 'Bu8qQPQ9YjcPWruoag_t_GRXxn9CyRmgPNG4DCJT'
    base_url: 'http://dev-wellness-survey.finc.com'
  light_survey_url: 'http://dev-wellness-survey.finc.com/oauth/authorization'
  personal_survey_url: 'http://dev-wellness-survey.finc.com/oauth/authorization/personal_survey'
  finish_url: 'fincapp://wellness-survey-callback'
  mental_care_url: 'http://dev-wellness-survey.finc.com/oauth/authorization/mental_care'
wellness_ai:
  api:
    version: v1
    access_grant: 'o2PtCedv5V1ATXAUTRsAf-9GhZ41Lx4E6AchCnzn_7tKc66k8uL1dfxH-pqcusZr'
    application_token: 'development'
    base_url: 'http://dev-ai.finc.com'
finc_account_manager:
  enable: true
  api:
    version: v1
    access_grant: '4CUnecg4KacURjSy8Hbx22RNkiL8zaLSN2HaXTUCyQD-XcdkPFS3DKyRjhRr'
    base_url: 'http://dev-fam.finc.com'

fi_chat:
  api:
    base_url:
    access_grant: fichataccessgrant
    application_token: fichataccessgrant

aws:
  access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  fog_directory: "requl-development"
  cognito:
    identity_pool_id: <%= ENV['AWS_COGNITO_IDENTITY_POOL_ID'] %>
    identity_provider_name: <%= ENV['AWS_COGNITO_IDENTITY_PROVIDER_NAME'] %>
secrets:
  secret_key_base: ed6a7b55dd4e8afeadd390066c76df88223810c0fcdf95628d7222ba4b2f8c8e4cdb2d0fa039bf8004d3aece62d0514cfa8303cac7a3c6c2c32eab56a1972a04

mailer:
  host: 'localhost:3000'
  user_name: 'YOURMAILEREMAIL@finc.com'
  admin:
    from: オンラインワークス事務局 <info-ow@finc.co.jp>
    user_name: info-ow@finc.co.jp
  user:
    from: FiNC <info@finc.com>
    user_name: 'info@finc.com'
  finc_developer:
    from: FiNC Developer <info@finc.com>
    user_name: 'info@finc.com'
    bcc: []
  send_only:
    from: '"【FiNCサポートセンター（自動配信）】" <no-reply-fincapp@finc.com>'
    user_name: no-reply-fincapp@finc.com
    bcc:
      default:
        - no-reply-fincapp@finc.com
      need_to_reply:
        - no-reply-fincapp@finc.com
        - support-fincapp@finc.com
  support_center:
    from: '"【FiNCサポートセンター】" <support-fincapp@finc.com>'
    user_name: support-fincapp@finc.com

slack:
  finc_account_manager:
    channel_url: ''
    test_channel_url: ''
    channel: '#fam_test'
  requl_mobile:
    url: ''
    channel: '#diet_coach_develop'
  fi_chat:
    url: ''
    channel: ''
  rake:
    finc_app_tag:
      url: ''
      channel: '#dc_warning_staging'

db:
  default:
    username: root
    password: root
    host: mysql_utf8mb4
    port: 3306
  genetic_test:
    username: 'YOUR DB USERNAME HERE'
    password: 'YOUR DB PASSWORD HERE'
    database: genetic_test_development
    socket: /tmp/mysql.sock

errbit:
  api_key: 4c9a8ba8c4ee17ac0d20a7f746e865e8

finc_services:
  access_grants:
    - 219bdc9725e75b85b94a1a40716732f5586212c7b5987d27a5db1d39876acfbe
    - de9da7a04e7bb21b0219a93a8b1b5ed98d00cf4c24f8f9701e1fb5062ca18ab5
    - Bu8qQPQ9YjcPWruoag_t_GRXxn9CyRmgPNG4DCJT
    - o2PtCedv5V1ATXAUTRsAf-9GhZ41Lx4E6AchCnzn_7tKc66k8uL1dfxH-pqcusZr
    - 4CUnecg4KacURjSy8Hbx22RNkiL8zaLSN2HaXTUCyQD-XcdkPFS3DKyRjhRr
    - fichataccessgrant

laerdal:
  application_token: <%= ENV['LAERDAL_ACCESS_TOKEN'] %>

sbi_life:
  tmp_user:
    sign_up_with_email:
      auth_token: <%= ENV['SBI_LIFE_TMP_USER_SIGN_UP_WITH_EMAIL_AUTH_TOKEN'] %>
    new:
      blank_mail:
        mailto_address: ''
