allow_push_notification: false

omniauth:
  facebook:
    app_id: 193538350855275
    app_secret: 486ef72737ddbcce023528971421be30
  twitter:
    app_key: hkVnha9e4asFz2zH5sEma2vHn
    app_secret: Gc9RV7ko8kQo40KMiFI4EfpoWNdIU7PJoCXN8npg6USA1cDe1j
  fitbit:
    client_id: 'test_client_id'
    client_secret: 'test_secret'
    redirect_uri: "http://localhost:3000/web_views/fitbit_auth/authorized_callback"
    scope: [activity sleep weight]
gcm:
  api_key: "AIzaSyAQt-IMoplXguqC6gj8hrS3NNZeVRsAKO8"
apns:
  certificate_file_names:
    - 'dummy_for_test.pem'
admin_password:
  secret_key: 'cb98d90c2d09a5f7cb8beb7fa94e7cafd3689ce203d92a5a01'
  cipher: 'aes-256-cbc'
test_email: engineers_finc@googlegroups.com

base_url: 'http://127.0.0.1'
finc_store:
  base_url: 'http://localhost:3000'
  sb:
    base_url: 'http://localhost:3000'
  api:
    access_grant: 'test_access_grant'
finc_app:
  consumer_key: 'M4HXT1y4-xuyoKE1DgHu4wtWyYX4P5BaTxsWf7Kp'
  consumer_key_for_online_works: 'ow_test_token'
genetic_test:
  database:
    database: "genetic_test_test"
  api_version: v1
  api:
    access_grant: '9e9955423ed6eafcb5b69092cfa654ec39b36846e60f26f94766238439547f83'
secrets:
  secret_key_base: ed6a7b55dd4e8afeadd390066c76df88223810c0fcdf95628d7222ba4b2f8c8e4cdb2d0fa039bf8004d3aece62d0514cfa8303cac7a3c6c2c32eab56a1972a04
customer_manager:
  api:
    access_grant: 'de9da7a04e7bb21b0219a93a8b1b5ed98d00cf4c24f8f9701e1fb5062ca18ab5'
wellness_survey:
  api:
    version: v1
    access_grant: 'tX2H8n4znrZAjb_mRp2zSm7h3UKzbAcUGBm9KjHj'
    base_url: 'http://test-wellness-survey.local'
  light_survey_url: 'https://test-wellness-survey.local/oauth/authorization'
  personal_survey_url: 'https://test-wellness-survey.local/oauth/authorization/personal_survey'
wellness_ai:
  api:
    version: v1
    access_grant: 'o2PtCedv5V1ATXAUTRsAf-9GhZ41Lx4E6AchCnzn_7tKc66k8uL1dfxH-pqcusZr'
    base_url: 'http://wellness-ai.test'
finc_account_manager:
  enable: true
  api:
    version: v1
    access_grant: fam_test_access_grant
    base_url: 'http://fam.finc.local'
fi_chat:
  api:
    base_url:
    access_grant: fichataccessgrant
    application_token: fichataccessgrant
  direct_chat:
    official_account:
      finc_information_id: 1
      broadcast_sendable_ids:
        - 1

fi_chat_client:
  api:
    base_url: 'https://local.finc.com'
company_account_manager:
  api:
    access_grant: 'testgrant'
    application_token: 'testtoken'

online_works:
  api:
    base_url: http://test-online-works.local
    access_grant: '8k-6VLTgSPow-UG7Sk4siy7si5rBZJhjAPkNpfYU'

o2o_client:
  base_url: ''
o2o:
  api:
    application_token: ''
  base_url: ''

push_notifier:
  api:
    access_grant:
    base_url:

rankie:
  api:
    access_grant: abcd
    base_url: 'http://127.0.0.1'

finc_app_web_client:
  base_url: ''

activity_timeline:
  api:
    base_url:
    application_token:

try_content:
  tmp:
    sakura_comment:
      enabled_user_ids:
        - 1

aws:
  access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  fog_directory: "requl-development"
  elastic_transcoder:
    promotion_movie:
      pipeline_id:
      sqs_endpoint:
      preset_id:
        mobile_movie:
        web_movie:
      uploadable_official_account_ids:
        - 1
  cognito:
    identity_pool_id: <%= ENV['AWS_COGNITO_IDENTITY_POOL_ID'] %>
    identity_provider_name: <%= ENV['AWS_COGNITO_IDENTITY_PROVIDER_NAME'] %>

secrets:
  secret_key_base: ed6a7b55dd4e8afeadd390066c76df88223810c0fcdf95628d7222ba4b2f8c8e4cdb2d0fa039bf8004d3aece62d0514cfa8303cac7a3c6c2c32eab56a1972a04

mailer:
  host: 'localhost:3000'
  user_name: 'YOURMAILEREMAIL@finc.co.jp'
  admin:
    from: オンラインワークス事務局 <info-ow@finc.co.jp>
    user_name: info-ow@finc.co.jp
  user:
    from: FiNC <info@finc.co.jp>
    user_name: 'info@finc.co.jp'
  finc_developer:
    from: FiNC Developer <info@finc.co.jp>
    user_name: 'info@finc.co.jp'
    bcc: []
  send_only:
    from: '"【FiNCサポートセンター（自動配信）】" <no-reply-fincapp@finc.com>'
    user_name: no-reply-fincapp@finc.com
    bcc:
      default:
        - no-reply-fincapp@finc.com
      need_to_reply:
        - no-reply-fincapp@finc.com
        - support-fincapp@finc.com
  support_center:
    from: '"【FiNCサポートセンター】" <support-fincapp@finc.com>'
    user_name: support-fincapp@finc.com

partner_organization:
  blank_mail:
    address: 'apply-stg@inbound.finc.com'
    access_token: 'x8yq5tafigjvfx25w4xyddygjfti9xykpvzx--wt'

slack:
  finc_account_manager:
    channel_url: ''
    test_channel_url: 'http://test.slack'
    channel: '#fam_test'
  requl_mobile:
    url: 'http://test.slack'
    channel: '#diet_coach_develop'
  fi_chat:
    url: ''
    channel: ''
  activity_timeline:
    url: ''
    channel: ''
  rake:
    finc_app_tag:
      url: 'https://finc.slack.com'
      channel: '#dc_warning_staging'

db:
  default:
    username: #'YOUR DB USERNAME HERE'
    password: #'YOUR DB PASSWORD HERE'
    #socket: /tmp/mysql.sock
  genetic_test:
    username: 'YOUR DB USERNAME HERE'
    password: 'YOUR DB PASSWORD HERE'
    database: genetic_test_test
    socket: /tmp/mysql.sock

redis:
  host: localhost
  port: 6379
  namespace: <%= [Rails.application.class.parent_name, Rails.env].join(':') %>

sidekiq:
  redis:
    host: localhost
    port: 6379

errbit:
  api_key: 4c9a8ba8c4ee17ac0d20a7f746e865e8

finc_services:
  access_grants:
    - 219bdc9725e75b85b94a1a40716732f5586212c7b5987d27a5db1d39876acfbe
    - de9da7a04e7bb21b0219a93a8b1b5ed98d00cf4c24f8f9701e1fb5062ca18ab5
    - tX2H8n4znrZAjb_mRp2zSm7h3UKzbAcUGBm9KjHj
    - o2PtCedv5V1ATXAUTRsAf-9GhZ41Lx4E6AchCnzn_7tKc66k8uL1dfxH-pqcusZr
    - 4CUnecg4KacURjSy8Hbx22RNkiL8zaLSN2HaXTUCyQD-XcdkPFS3DKyRjhRr
    - fichataccessgrant
    - 8k-6VLTgSPow-UG7Sk4siy7si5rBZJhjAPkNpfYU

from_scratch:
  sftp:
    server_host: ftp.fs-bdash.com
    username: bd_bmhqca_1
    identity_key: /home/ubuntu/.ssh/f_scratch_rsa

sb:
  cindy:
    client_id: ''
    client_secret: ''
    authentication:
      fetch_code:
        url: 'http://example.com'
        redirect_uri_for_sign_up: 'https://staging-pksapp.finc.com/users/oauth/cindy/callback'
        redirect_uri_for_sign_in: 'https://staging-pksapp.finc.com/users/oauth/cindy_sign_in/callback'
        redirect_uri_for_cancel: 'https://staging-pksapp.finc.com/users/oauth/cindy/callback/cancel'
      fetch_access_token:
        url: 'http://example.com'
        redirect_uri: 'http://example.com'
      check_contracted:
        url: 'http://example.com'
    service:
      contents_service_id: '111'
      usage_status:
        url: 'http://example.com'
      start_billing:
        url: 'http://example.com'
      stop_billing:
        url: 'http://example.com'
  healthcare:
    application_id: 'app'
    summary:
      url: 'http://example.com'
    detail:
      url: 'http://example.com'
    started:
      url: 'http://example.com'
      redirect_uri: 'http://example.com'
    canceled:
      url: 'http://example.com'
      redirect_uri: 'http://example.com'
  sftp:
    host: ftp0001
    username: ubuntu
    options:
      identity_keys: '/path/to/your/identity_key'
      port: 22

spec_helper:
  enable_seed_fu: true
  enable_grape: true
  enable_coverage: true

laerdal:
  application_token: laerdal_app_token

sbi_life:
  tmp_user:
    sign_up_with_email:
      auth_token: <%= ENV['SBI_LIFE_TMP_USER_SIGN_UP_WITH_EMAIL_AUTH_TOKEN'] %>
    new:
      blank_mail:
        mailto_address: 'sbi-apply-test@inbound.finc.com'

sfdc:
  help_url:
    consumer_key: <%= ENV['SFDC_HELP_URL_CONSUMER_KEY'] %>
    salt: <%= ENV['SFDC_HELP_URL_SALT'] %>
    url: 'https://dev3-finc.cs6.force.com/faq'

pre_registration:
  android_token:
    authentication_token: 'test_authentication_token'
  ios_token:
    authentication_token: 'test_authentication_token'

pre_registration_user:
  authentication_token: 'test_authentication_token'
